### ISSUE TITLE
Could you please write a pytorch version of test_cross_date.py  or test_demo.py ,so that I can understand better 

### ISSUE THREAD

**Issue by iqaBeginner** [lidq92/SFA#5] opened 2020-05-04 09:29 UTC
[https://github.com/lidq92/CNNIQA/blob/master/test_cross_dataset.py](url)
[https://github.com/lidq92/CNNIQA/blob/master/test_cross_dataset.py](url)
just like the CNNIQA project.
I am also a little confused where did you save the model ?

waiting for your reply~

**Comment by lidq92** [comment] 2020-05-04 10:26
@iqaBeginner You can just refer to my other IQA projects and the MATLAB version file.

SFA model uses the pre-trained ResNet-50 to extract features, and you only need to save the trained PLSR models for quality prediction (i.e., plsr10_1, plsr10_2, plsr10_3 in [https://github.com/lidq92/SFA/blob/master/SFA-pytorch/SFA.py](https://github.com/lidq92/SFA/blob/master/SFA-pytorch/SFA.py)), then load it when you need to do the test.

You can also refer to the discussion in the previous issues #1 #3 #4.

**Comment by iqaBeginner** [comment] 2020-05-08 15:19
Hi, I successfully run SFA.py, but I find that the results are much lower than your paper's result.
Median results:
[ **0.75924501**  0.56755957  **0.78426466** 12.7943511   1.28755365]
The Pytorch version seems to have bad results.

**Comment by lidq92** [comment] 2020-05-09 00:49
@iqaBeginner Have you ever read the Remark in [README](https://github.com/lidq92/SFA/tree/master/SFA-pytorch)? 
To make it clear to you, I detail some important things as follow.

I implemented the Pytorch version as an illustration for people who wanted.
**The reported results in the paper are obtained by Caffe framework.**
You should know the major differences between these two versions are the pre-trained model and the corresponding pre-processing step.

Suggestion:
To obtain the results reported in the paper with PyTorch, one should transfer the ResNet-50 Caffemodel weights to PyTorch correctly and use the corresponding pre-processing step.
There are many resources on the web that tell you how to transfer the Caffemodel, you may have a try.
(By following this suggestion, you may obtain the reported results in the paper or similar results since there are still other differences, e.g., the numerical computation in different software/frameworks may have different numerical precision.)

**If you want to compare the SFA model in your research, please use the original Caffe+MATLAB version for training and testing in the same settings as yours.**
If you want to improve the SFA model and you use the PyTorch framework, you can follow the above suggestion and refer to the [illustration](https://github.com/lidq92/SFA/blob/master/SFA-pytorch/SFA.py).
I am not free now, it is not in my first priority list.
When I am free, I may add my PyTorch implementation that can reproduce the paper.

By the way, you should learn to analyse your problem by yourself.
The differences between these two versions are obvious that I think you should find by yourself.
Also, you have the template for `test_demo.py`, so why not implement it by yourself first? If you have any question during your implementing process, at that time, you may open an issue for help.

Correspondingly, Here are two research suggestions for you,  a freshman in the field of I/VQA (same for other research fields).
- **Asking a question is not bad, but asking the question without any thinking is not a good learning way.**  
- **Try to "do" it by yourself if you want to learn something.**

Finally, 
Good luck to you.

**Comment by iqaBeginner** [comment] 2020-05-10 14:30
Thank you for your reply
I have some ideas, and want to improve the SFA model and I use the PyTorch framework.
As a freshman, I am not able to reproduce the results in Pytorch.(sorry,  I tried a lot, but failed,)
I understand these are very trivial for a man of your stature in programming, but for nubes…I appreciate your response and thank you in advance if you could reprodece the results in Pytorch.

**Comment by lidq92** [comment] 2020-05-11 01:41
@iqaBeginner If still not having any idea, you can have a look at my update.

For not getting a freshman down, I added more in this project [SFA-pytorch](https://github.com/lidq92/SFA/tree/master/SFA-pytorch). Now the PyTorch implementation for the conference version is almost the same as the Caffe implementation. And the transferred models can provide similar (but slightly worse) results, SROCC=0.8036, PLCC=0.8220, and OR=0.86%.

**Comment by iqaBeginner** [comment] 2020-05-12 06:01
**Thank you very much** for your help!!!
I ran the updated code and got almost the same result in **CLIVE, BID,LIVE** database .
CLIVE SROCC=0.8036640  PLCC=0.8219469  
BID SROCC=0.82018048 PLCC=0.82528043 
LIVE SROCC=0.950
Now I'm a little confused about the result in **TID2008**
In the paper, the SROCC result about the TID2008 database is **0.9098**
I copy the corresponding TID2008fullinfo.mat files from [https://github.com/lidq92/CNNIQA/tree/master/data](url) ,and got the result as followed
SROCC=0.69943111 PLCC=0.74398422
Could you explain my confusion when you are free.
I'm **so sorry** to bother you again.

**Comment by lidq92** [comment] 2020-05-12 06:06
@iqaBeginner This code is only for quality assessment of blur-dominated images.
For TID and LIVE, you should use only the blur images.
The data information is provided in this project [data](https://github.com/lidq92/SFA/tree/master/data).

You should patiently read the papers and the whole project.

**Closed as completed** 2020-05-17 01:41 UTC
